import Head from 'next/head'
import DashboardLayout from '../components/Dashboard/DashboardLayout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NURTURE LABS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout />
    </div>
  )
}
