import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DashboardLayout from '../components/Dashboard/DashboardLayout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NURTURE LABS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h5 className='bg-[#3772FF] text-white py-2 text-1xl font-semibold text-center '>Lorem Ipsum is simply dummy text of the printing</h5>

      <DashboardLayout />

    </div>
  )
}
